apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cluster2-466c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cluster2-466c"
  template:
    metadata:
      labels:
        app: "cluster2-466c"
    spec:
      containers:
        - name: "cluster2-466c"
          image: "myactionnewacr.azurecr.io/cluster2"
          ports:
          - containerPort: 80