apiVersion: v1
kind: Service
metadata:
    name: "githubrunner-ce46"
    labels:
        app: "githubrunner-ce46"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "githubrunner-ce46"