on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myactionnewacr.azurecr.io
        username: ${{ secrets.acr_myactionnewacr_username }}
        password: ${{ secrets.acr_myactionnewacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t myactionnewacr.azurecr.io/cluster2:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push myactionnewacr.azurecr.io/cluster2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cluster2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cluster28409 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cluster28409`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cluster28409
        container-registry-url: myactionnewacr.azurecr.io
        container-registry-username: ${{ secrets.acr_myactionnewacr_username }}
        container-registry-password: ${{ secrets.acr_myactionnewacr_password }}
        secret-name: cluster2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cluster28409
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          myactionnewacr.azurecr.io/cluster2:${{ github.sha }}
        imagepullsecrets: |
          cluster2dockerauth
