on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: actionrunneracr.azurecr.io
        username: ${{ secrets.acr_actionrunneracr_username }}
        password: ${{ secrets.acr_actionrunneracr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t actionrunneracr.azurecr.io/githubrunner:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push actionrunneracr.azurecr.io/githubrunner:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_githubrunner_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: actionrunneracr.azurecr.io
        container-registry-username: ${{ secrets.acr_actionrunneracr_username }}
        container-registry-password: ${{ secrets.acr_actionrunneracr_password }}
        secret-name: githubrunnerdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          actionrunneracr.azurecr.io/githubrunner:${{ github.sha }}
        imagepullsecrets: |
          githubrunnerdockerauth
